version: '3.8'

services:
  app:
    image: 'codecool/seasonal-product'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
    - DATABASE_URL=jdbc:postgresql://db:5432/seasonal_product?user=postgres&password=compose-postgres



  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=seasonal_product